inherit_from:
  - .rubocop_todo.yml

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Metrics/LineLength:
  Max: 120

Lint/HandleExceptions:
  Exclude:
    - 'Rakefile'

Metrics/BlockLength:
  Exclude:
     - 'spec/**/*'
